### PR TITLE
Optimize and add new ordering modes.

### PR DESCRIPTION
**Pull request by karliss**
* Faster implementation of shortest path using KD-tree . Also consider both ends of paths.
* Hilbert curve and Z-order ordering modes. Not as good result as greedy shortest path, but almost as fast as sorting by axis.

The use of KD-tree didn't give as much improvement as I hoped. Still it gave an improvement from ~6s to 0.5s on a file with 10K lines and that's while considering both ends of path. I guess in the few thousand range the olf brute force O(n2) aproach isn't crazy slow yet.  Considering boths ends of path when looking for closest one, helps a lot with parallel lines as it allows creating back and forth zig zag pattern. Doesn't help for closed paths, which have start and end points in the same place.
Didn't test too much with even bigger files as at that point importing svg was getting very slow.

Also added two space filling curve based sorting approaches. They work almost as fast simply sorting by axis (at least relative to shortest path), while still giving reasonable results.

Some screenshots:
Hilbert curve on regular grid of circles:
image
z-curve on regular grid of circles
image
Hilbert on randomized points
image
z-curve on randomized points
image
Shortest path on randomized points
image
Comparison of Normal, Y, Shortest path, Hilbert and Z curve on a more complex drawing
image

### CODE REVIEW

**Comment by frmdstryr** [comment]
Thanks for adding these and taking the time to include screenshots. Very interesting results. Definitely looks like an improvement over my dumb greedy solver.

Can you please use the atom framework for the KD tree and there is a function with a random indent.

**Comment by karliss** [comment]
> Can you please use the atom framework for the KD tree

I am not against it. Can you give me a bit more context, so that I can make better choices in future. How does atom framework help in this situation? I understand that in different situations it helps dealing with serialization code, property synchronization with enaml UI. Those don't seem to be a problems for KDTree used in shortest path ordering mode, which is only a temporary structure to accelerate the OrderShortestPath.order and doesn't live longer than single function call.

**Comment by frmdstryr** [comment]
It helps by documenting the types and prevents tacking random/incorrect attributes (eg typos) on objects.

**Comment by karliss** [comment]
Thanks those are good reasons. Will update the PR.

I guess later versions of python3 achieves more or less the same with type attributes. But that's not very helpful for inkcut taking into account versions it claims to support and fact that atom is required anyway for integration with enaml.

**Comment by karliss** [comment]
Update the PR by converting KDTree to atom and fixing the indentation for one function.

**Comment by frmdstryr** [comment]
A few functions are used as static methods but not annotated with `@staticmethod`. 

On Qt6 the Z-curve is throwing an error:
```python-traceback
  File "/home/usr/projects/inkcut/inkcut/job/models.py", line 273, in _default_optimized_path
    doc = OrderingHandler().order(self, doc)
  File "/home/usr/projects/inkcut/inkcut/job/ordering.py", line 320, in order
    res = self.order_by_func(
  File "/home/usr/projects/inkcut/inkcut/job/ordering.py", line 39, in order_by_func
    subpaths = sorted(split_painter_path(path), key=sort_func)
  File "/home/usr/projects/inkcut/inkcut/job/ordering.py", line 321, in <lambda>
    job, path, lambda p: self.curve_pos(start_point(p), p0, max_size))
  File "/home/usr/projects/inkcut/inkcut/job/ordering.py", line 358, in curve_pos
    p = p.toPoint() - p0
```
Qt5 would cast automatically, Qt6 does not so they all need to use QPoint or QPointF.

**Comment by frmdstryr** [comment]
> Thanks those are good reasons. Will update the PR.
> 
> I guess later versions of python3 achieves more or less the same with type attributes. But that's not very helpful for inkcut taking into account versions it claims to support and fact that atom is required anyway for integration with enaml.

Python 3 type annotations do not do runtime type checking but atom does.

Eg 
```python
class Person:
    name: str = ""
   
p = Person()
p.name = False
p.name
Out[5]: False
```

Vs

```python
from atom.api import Atom, Str

class Person(Atom):
    name = Str()
    
p = Person()
p.name = False
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [9], line 1
----> 1 p.name = False

TypeError: The 'name' member on the 'Person' object must be of type 'str'. Got object of type 'bool' instead.
```

In almost every case this saves debugging time.

**Comment by frmdstryr** [comment]
Looks good. Thanks!

**Pull request merged**
