### PR TITLE
Added new flavor (#7) of the DMPL protocol

### PR DESCRIPTION
**Pull request by LDP-Soft**
... to allow the Creation PCut CT-630 to work. The 630 requires special initialization and finish commands. Tested with PCut CT-630. Initialization, moving, cutting and finalization work. No hangs.
This is a new flavor of the protocol so it does not affect existing devices or existing protocols or flavors.

### CODE REVIEW

**Comment by karliss** [comment]
If it's a device specific initialization sequence it doesn't need a separate protocol mode. It should be possible to specify  it in the driver manifest file (there are currently no examples of it, but I think I tried it before). Creating a  new arbitrary numbered protocol mode for each plotter doesn't seem scalable.

In my opinion protocol versions/mode should be used more if it's one or multiple of these factors:
* it's a documented version of the protocol defined by  inventors of protocol
* it's a variant of the protocol used by specific manufacturer/or device firmware family 
* there are many devices using the same variant
* the version needs to be recognizable and named in a way that inkcut user has a way of knowing their device supports/requires specific variant 

As a sidenote I am slightly sceptical about the current DMPL mode 6, "IN;" plus "PD" "PU" looks more like HPGL than DMPL.

Note I am not the maintainer so take my opinion with grain of salt.

**Comment by LDP-Soft** [comment]
> If it's a device specific initialization sequence it doesn't need a separate protocol mode. It should be possible to specify it in the driver manifest file (there are currently no examples of it, but I think I tried it before).

That would be nice if I could create a driver manifest instead of adding a protocol flavor.
I could not and still cannot find any documentation on the manifests. Any help would be appreciated. If I can drive the device using a manifest, I can scrap this review.

**Comment by karliss** [comment]
Here is an example you might find useful. The specific config values themselves doesn't necesarry make sense for specific device, it just demonstrates how to set them.

```
        DeviceDriver:
            manufacturer = 'AAAA DMPL test'
            model = 'Model name'
            width = '120cm'
            protocols = ['dmpl']
            connections = ['serial', 'printer']
            default_config = {
                'commands_connect': ';:H A L0 ECN U ',
                'commands_disconnect': ' U F @ ',
                'protocol' : {
                    'dmpl': {
                        'mode': 1
                    }
                }
            }
```

You would still have to decide how to deal with combination of init commands set in protcol by connection_made and the device config. Gcode protocol has a flag for disabling builtin startup commands, but dmpl currently doesn't although you might get away without it.

It seems like currently the ones from protocol are called first. So maybe you could use mode 1 which does ";:HAEC1"
and in device specific config put "L0 ECN". 

It's not magic but just a sequence of multiple DMPL commands, many of which should work in different order and also be overridable. Not every plotter might support every mode, and there might be some quirks in the command parser, but I would expect any sane implementation to parse them like commands instead of expecting fixed magic string.  
The stuff you listed consists of:
```
;: - initialize mode one (also should enable XON/XOFF base flow control) one of the few commands which really needs to be at start
 H - home
 A - absolute coordinates
 L0 - line style 0
 ECN - use 0.025mm as unit, (alternative values EC1 -0.001 inch EC5 - 0.005 inch , ECM 0.1mm)  
 U - lift pen, I don't see a point doing this after homing, if pen was down I would have expected it to already make a mess during home
```

mode  1 has
```
;: - init mode 1 without any space at the start
H - home
A - absolute mode
EC1 - you wanted ECN, but it should be possible to override this at any time
```

**Comment by LDP-Soft** [comment]
That looks straight forward, thank you.
Not coincidentally, that's the same DMPL reference guide I was using to learn to communicate with my cutter properly.
I made the manifest file but how do I reference it from InkCut now?

**Comment by karliss** [comment]
Yes just add it in the drivers/manifset.enaml same place as others.

**Comment by LDP-Soft** [comment]
> Yes just add it in the drivers/manifset.enaml same place as others.

I do not seem to be able to get InkCut to honor the settings in the driver manifest enaml file. InkCut reads the file and enumerates all the devices listed but does not honor the extra commands. I will have to open a new issue for that (if one does not exist yet) and I could also look into it and hopefully fix it.

Thank you for your help, I will discard this review.

**Comment by karliss** [comment]
In my tests it seemed to work. I didn't just gave you an example without testing that it produces expected device config.

Did you create  a new device after adding or modifying the manifest entry? 

Did you  what do you mean buy not honor the extra command? Did it not show in corresponding tab of newly created device config. Or did it show but, but not get executed when sending data to device?

**Comment by LDP-Soft** [comment]
> In my tests it seemed to work. I didn't just gave you an example without testing that it produces expected device config.
> 
> Did you create a new device after adding or modifying the manifest entry?
> 
> What do you mean buy not honor the extra command? Did it not show in corresponding tab of newly created device config. Or did it show but, but not get executed when sending data to device?

Correct, I created a new device with the extra pre-connect and pre-disconnect commands.
When I launched InkCut and selected the new device, I checked under the Device tab and the pre-connect and pre-disconnect commands were not in the text boxes.
I will dig through the code that loads the device driver manifest file and see if maybe the options in my manifest are labeled differently and I will report back.

**Comment by LDP-Soft** [comment]
> It seems like currently the ones from protocol are called first. So maybe you could use mode 1 which does ";:HAEC1" and in device specific config put "L0 ECN".

To give a little more detail: I tried to initialize my cutter with the initialization strings for all 4 DMPL protocols and none of them worked.
Worst case scenario, I will keep the modified source on my cutter PC and live with that, it's not a bad workaround.

**Comment by karliss** [comment]
Feel free to attach the mainfest you tried so that I can compare it against my experiment.

**Comment by LDP-Soft** [comment]
> Feel free to attach the mainfest you tried so that I can compare it against my experiment.

Below you will find my drivers manifest file.
Since this board does not recognize the .enaml extension, I had to upload it with a .txt extension, sorry.

When I launch InkCut and create a new device (starts with "LDP-Soft"), it is added but the post-connect and pre-disconnect commands are not there.

[manifest.enaml.txt](https://github.com/user-attachments/files/16694951/manifest.enaml.txt)

**Comment by karliss** [comment]
Worked on my system. Although it chose hpgl, since that's what you have added first in the list of supported protocols. Probably will have to adjust that later as hpgl mode would likely need different after connect command (assuming your plotter supports both hpgl and dmpl), but that doesn't explain the commands not getting set.
image

Are you sure you are working with latest version of inkcut source code? The manifest file you sent lacks one of the changes from few years ago, this suggests that rest of the code might also be outdated.  The LDP-Soft:master branch looks fine, it has all the latest code including the part which is missing in manifest.enaml.txt you sent.

**Comment by LDP-Soft** [comment]
> Are you sure you are working with latest version of inkcut source code? The manifest file you sent lacks one of the changes from few years ago, this suggests that rest of the code might also be outdated.

That is a good question. I installed InkCut via pip3 just 2 weeks ago. The EXE (I am on Windows) does not have any versioning information but when I launch the program, it announces itself as version 2.1.6.  The InkCut source page here lists 2.1.5 as the latest.

Glad the new device in my manifest file worked for you. Now I'd love to make it work for me.
I want to avoid any drastic measures such as grabbing all source from GitHub and blindly overwriting the source in the installed folder.
Do you have any suggestions on what to try next?

**Comment by LDP-Soft** [comment]
> No idea where you got 2.1.6. Where exactly do you see that announces itself as "2.1.6"? The latest release in[ github releases](https://github.com/inkcut/inkcut/releases) is 2.1.5, the latest version in [pypy](https://pypi.org/project/inkcut/#history) (the python package repository from which pip installs stuff) is 2.1.5. If you install the package using `pip install inkcut` and list installed packages with `pip list` it says "2.1.5". If you run it, it says 2.1.5 in the terminal. Even if you take latest source code from the master branch on github, it says 2.1.5.

Isn't that an interesting thing? The 2.1.6 is displayed in the log (and cmdline) when I run the installed InkCut.

2024-08-21 08:53:47,769 | INFO    | inkcut | ========================================
2024-08-21 08:53:47,769 | INFO    | inkcut | Inkcut launched
2024-08-21 08:53:47,769 | INFO    | inkcut | Version: 2.1.6
2024-08-21 08:53:47,769 | INFO    | inkcut | Python: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:34:34) [MSC v.1928 32 bit (Intel)]


I found the version number in plain text in the __init__.py file in the main InkCut folder.
%userprofile%\AppData\Roaming\Python\Python38\site-packages\inkcut
The version variable in that file seems to dictate the version that InkCut writes to the log.

**Comment by LDP-Soft** [comment]
> Installing the version from pip is only useful for end users which aren't going to touch the source code. If you work with source code there is no need to install inkcut to run it.

Agreed. I originally installed InkCut from pip because I only intended to use it.
But since I could not make it work with my cutter and because it is open source Python, I though I'd pull the source from GitHub and give it a shot to adapt it to run my cutter. Successfully,

That explains why I have two copies.
I will remove the installed InkCut copy and stick with the source version.

Thank you for your help.

**Pull request closed without merging**
