### PR TITLE
Fix 259 : import submodule directly

### LINKED ISSUE #259: Kubuntu 20.04 plug-in inkscape>Inkcut error
Traceback (most recent call last):
  File "inkcut_cut.py", line 27, in <module>
    optparse_spec = importlib.util.find_spec("optparse")
AttributeError: module 'importlib' has no attribute 'util'

sorry for my english
if you need more information please tell me how to get it

### PR DESCRIPTION
**Pull request by aaujon**
Try to fix #259

### CODE REVIEW

**Comment by frmdstryr** [comment]
I think Inkscape versions less than 1.0 use python 2 where importlib util doesn't exist.  Maybe instead of checking for the existence of optparse it'd be better to just check the python version?

```
Python 2.7.17 (default, Apr 15 2020, 17:20:14) 
[GCC 7.5.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import importlib
>>> importlib.util
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'util'
```

**Comment by aaujon** [comment]
some thing like that :
`import sys
if sys.version_info[0] < 3:
    VERSION='0.9X'`
but i'm pretty sure that on my previous fedora (30 or 31) I was running inkscape 0.9 with python 3, so checking python version is actually bad on some cases. I will update this PR.

**Comment by frmdstryr** [comment]
Maybe the best route would be to just check based on what attributes the `inkex` module has then?

Also `from lxml import etree` works on all versions so the usage of `inkex.etree` can be removed.

**Comment by raboof** [comment]
> I think Inkscape versions less than 1.0 use python 2

Inkscape 0.92.5 actually adds support for Python 3. This PR fixes Inkscape 1.x for me.

When I test with Inkscape 0.92.5-and-python3 this is still broken for me (though I don't necessarily care about that)

**Pull request merged**
